[package]
name = "nrf9160_flash_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf9160-hal = {version = "0.16.0", optional = true}
cortex-m = "0.7.4"
cortex-m-rt = "0.7.2"
